# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'NotifeeCore' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for NotifeeCore
  pod 'AFNetworking'
  pod 'PromisesObjC'
end
