name: Docs Deployment
on:
  push:
    branches:
      - main
    paths:
      - 'docs-react-native/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Netlify Build Hook
        run: curl -s -X POST -d {} "https://api.netlify.com/build_hooks/${TOKEN}"
        env:
          TOKEN: ${{ secrets.NETLIFY_TOKEN }}
